config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  root 'sessions#home'
  #nested routes for comments
    resources :posts do
      resources :comments, only: [:index, :new, :create]
    end

  resources :posts
  resources :likes, only: [:create, :destroy]
  resources :users
  resources :followers
#   GET	/photos	photos#index	display a list of all photos
#   GET	/photos/new	photos#new	return an HTML form for creating a new photo
#   POST	/photos	photos#create	create a new photo
#   GET	/photos/:id	photos#show	display a specific photo
#   GET	/photos/:id/edit	photos#edit	return an HTML form for editing a photo
#   PATCH/PUT	/photos/:id	photos#update	update a specific photo
#   DELETE	/photos/:id	photos#destroy	delete a specific photo

  # LOGIN & LOGOUT
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get "/logout", to: "sessions#destroy"
  get "/homepage", to: "sessions#homepage"

  # USERS
  get '/register', to: 'users#register'
  post '/register', to: 'users#create'
  get "/users/:id", to: "users#show"

  #POSTS
  delete "/posts/:id", to: "posts#destroy"

  get "/friends", to: "users#index"

end

app/models/user.rb
class User < ApplicationRecord

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy


  has_many :active_relationship, class_name: "Follower", foreign_key: :"follower_id", dependent: :destroy
  has_many :passive_relationship, class_name: "Follower", foreign_key: :"followed_id", dependent: :destroy
  # has_many: This is a Rails association method that sets up a one-to-many relationship
  # :active_relationships: This is a symbolic name for this association. It’s used in the code to refer to this specific relationship.
  # class_name: "Follower": This specifies that the association is related to the Follower model.
  # foreign_key: :"follower_id": This tells Rails which column in the followers table should be used to link to the User model. In this case, follower_id refers to the ID of the user who is following someone else.
  # dependent: :destroy: This option indicates that when a user is deleted, any associated Follower records where the user is the follower will also be deleted.

  has_many :followed_users, through: :active_relationship, source: :followed_user
  has_many :follower_users, through: :passive_relationship, source: :follower_user
  # This lines essentially allows you to get all users that the current user is following:
  # current_user.follower_users


  def authenticate(psw)
    if psw == password
      true
    else
      false
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all

    following_ids = Follower.where(follower_id: session[:user_id]).pluck(:followed_id)
    # p "###### #{following_ids}"
    @following_users = User.where(id: following_ids).pluck(:username, :id)
  end

  # GET '/register', to: 'users#register'
  def new
    @user = User.new
  end


  # POST '/register', to: 'users#create'
  def create
    @user = User.new(user_params)

    if @user.save

      # get user id
      session[:user_id] = @user.id

      # get username
      session[:username] = @user.username

      redirect_to user_path(@user.id)

    else
      render :new
    end
  end

  # GET '/users/:id', to: "users#show"
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: @user.id).order(created_at: :desc)
  end

  def destroy
    p 'account deleted'
    @user = User.find(params[:id])
    if @user.id == session[:user_id] && @user.destroy
      flash[:notice] = "Your account has been deleted."
      session[:user_id] = nil # Clear the session
      redirect_to root_path # Redirect to the home page or login page
    else
      flash[:alert] = "There was a problem deleting your account."
      redirect_to user_path(@user)
    end
  end


  private
  def user_params
    # permit only -- takes only the parameters
    # require, permit -- takes user object first, then parameters within object -- object not created yet so user is empty
    params.permit(:username, :password)
  end

end

app/views/users/index.html.erb
<%= render partial: 'shared/nav' %>
<h1>My friends</h1>

<h3>People you follow</h3>
<% @following_users.each do |user| %>
  <li>
    <p>
      <%= link_to user[0], "users/#{user[1]}" %>
    </p>
     <%= button_to 'Unfollow', follower_path(user[1]), method: :delete, data: { confirm: 'Are you sure you want to unfollow this user?' } %>
  </li>
<% end %>

<h3>People you might know</h3>
<ul>
  <% @users.each do |user| %>
    <% if user.id != session[:user_id] && !@following_users.map(&:last).include?(user.id) %>
      <li>
        <p>
          <%= link_to user.username, "users/#{user.id}" %>
        </p>
        <%= button_to 'Follow', followers_path(follower: { followed_id: user.id }), method: :post %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/users/register.html.erb
<div class="login-container">
<h1> Register to Acebook</h1>

<%= form_with model: @user, url: register_path, local: true do |form| %>
    
    <div>
        <%= form.label :username %>
        <%= form.text_field :username, required: true %>
    </div>
    <div>
        <%= form.label :password %>
        <%= form.password_field :password, required: true %>
    </div>

    <div>
        <%= form.submit "Register" %>
    </div>
<% end %>
</div>

app/views/users/show.html.erb
<%= render partial: 'shared/nav' %>


<div>
  <% if @user.id == session[:user_id] %>
      <h1> Hi <%= @user.username %> !</h1>
  <% else %>
      <h1> Welcome to <%= @user.username %>'s page </h1>
  <% end %>
</div>


<% @posts.each do |post| %>

  <div>
    <h3><%= link_to post.message, post %></h3>

    <% if post.image.attached? %>
      <%= image_tag post.image, class: "image" %>
    <% end %>

    <h5>Posted: <%= post.created_at %></h5>

  </div>
  <p>
    <% if post.user_id == session[:user_id] %>
        <%= link_to "Edit", edit_post_path(post) %> |
        <%= link_to "Delete", post, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    <% end %>
  </p>
  <hr />

<% end %> 

<br>
<% if @user.id == session[:user_id] %>
  <%= link_to new_post_path do %>
    Add a New post
  <% end %>
<% end %>

<% if @user.id == session[:user_id] %>
  <%= button_to 'Delete Account', user_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete your account?" }%>
<% end %>

<!--<%= link_to logout_path do %>
  Log Out
<% end %>-->

<!-- <%= link_to friends_path do %>
  My Friends
<% end %> -->