config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  # Defines the root path route ("/")
  root 'sessions#home'
  #nested routes for comments
    resources :posts do
      resources :comments, only: [:index, :new, :create]
    end

  resources :posts
  resources :likes, only: [:create, :destroy]
  resources :users
  resources :followers
#   GET	/photos	photos#index	display a list of all photos
#   GET	/photos/new	photos#new	return an HTML form for creating a new photo
#   POST	/photos	photos#create	create a new photo
#   GET	/photos/:id	photos#show	display a specific photo
#   GET	/photos/:id/edit	photos#edit	return an HTML form for editing a photo
#   PATCH/PUT	/photos/:id	photos#update	update a specific photo
#   DELETE	/photos/:id	photos#destroy	delete a specific photo

  # LOGIN & LOGOUT
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get "/logout", to: "sessions#destroy"
  get "/homepage", to: "sessions#homepage"

  # USERS
  get '/register', to: 'users#register'
  post '/register', to: 'users#create'
  get "/users/:id", to: "users#show"

  #POSTS
  delete "/posts/:id", to: "posts#destroy"

  get "/friends", to: "users#index"

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  validates :user_id, presence: true

  # ActiveStorage association for image uploads
  has_one_attached :image
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end



  def create

    # created with params
    @post = Post.new(post_params)

    # added session to post
    @post.user_id = session[:user_id]

    # save! --- raises an error if fails
    if @post.save
      if params[:post][:image].present?
        # attach the image using ActiveStorage
        @post.image.attach(params[:post][:image])
      end
      redirect_to user_path(session[:user_id]), notice: 'Post created successfully'
    else
      render :new
    end
  end


  def index
    @posts = Post.all
  end


  def show
    @post= Post.find(params[:id])
    @comment = Comment.new
    @post.user_id = session[:user_id]
    render :show_post
  end


  def edit
    @post = Post.find(params[:id])
    if @post.user_id == session[:user_id]
      render :edit
    end
  end


  def update
    @post = Post.find(params[:id])
    if  @post.user_id = session[:user_id]
      if @post.update(post_params)
        redirect_to user_path(session[:user_id])

      else
        render :edit
      end
    end
  end


  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == session[:user_id]
      @post.destroy
      redirect_to user_path(session[:user_id])
    end
  end


  private
  def post_params

    # permit -- needs to be symbols only & refers to form fields
    params.require(:post).permit(:message, :image)
  end
end

app/views/posts/edit.html.erb
<%= render partial: 'shared/nav' %>
<h1>Edit Post</h1>

<%= form_for @post do |f| %>
    <p>
        <%= f.label :message %><br />
    </p>
        <p style="white-space: pre-line;">
        <%= f.text_area :message %>
    </p>
    <p>
        <%= f.submit "Update post" %>
    </p>

<% end %>

app/views/posts/index.html.erb
<%= render partial: 'shared/nav' %>

<% @posts.each do |post| %>
  <p>
    <%= post.message %>
  </p>
  <% if post.image.attached? %>
    <%= image_tag post.image %>
  <% end %>
<% end %>

<%= link_to new_post_path do %>
  New post
<% end %>

app/views/posts/new.html.erb
<%= render partial: 'shared/nav' %>
<%= form_with model: @post, local: true, html: { multipart: true } do |form| %>

  <%= form.label :message %>
  <%= form.text_field :message %>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>

  <%= form.submit "Submit Post" %>

<% end %>

app/views/posts/show_post.html.erb
<%= render partial: 'shared/nav' %>
<div>
  <h3><%= @post.message %></h3>

  <% if @post.image.attached? %>
    <%= image_tag @post.image, class: "image" %>
  <% end %>
  <h5>Posted: <%= @post.created_at %></h5>
</div>

<%= @post.likes.count %> Likes

<% current_user =  User.find(session[:user_id]) %>
<% like = current_user.likes.find_by(post: @post) %>

<% if like.nil? %>
  <%= button_to "Like", likes_path, params: { like: { post_id: @post.id }}, method: :post %>
<% else %>
  <%= button_to "Unlike", like_path(like), method: :delete %>
<% end %>

<p>
  <% if @post.user_id != session[:user_id] %>
    <%= link_to "Edit", edit_post_path(@post) %> |
    <%= link_to "Delete", @post, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
  <% end %>
</p>

<div id="comment-form" d="comment-form" style="margin-top: 20px; padding: 10px; border: 1px solid #ccc; border-radius: 8px; width: 100%;">
    <%= form_for [@post, @comment] do |f| %>
      <div style ="margin-bottom: 10px">
        <%= f.label :message_comment, "Leave a comment",  style: "font-size: 1.2em; font-weight: bold;" %>
      </div>
      <div>
        <%= f.text_area :message_comment, size: "60x10" %>
      </div>
        <%= f.hidden_field :post_id, value: @post.id %>
        <div>
        <%= f.submit "Add Comment" %>
        </div>
    <% end %>
</div>


<h3>Comments</h3>
<% @post.comments.reverse.each do |c| %>
  <div id="single-comment">
    <h4>Comment</h4>
    <h5>From - <%= c.user.username %></h5>
    <h6><%= c.message_comment %></h6>
  </div>
<% end %>


<hr />